server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://ip:3306/bookstore
    username: root
    password: 数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
source-dir:
  image-dir: /root/bookstore/
  image-map-url: static/image/**
